format = """
$username\
$hostname\
$directory\
${custom.jj}\
$cmd_duration\
$status\
$line_break\
$conda\
$character"""

command_timeout = 1000  # 1 second

[hostname]
ssh_symbol = ""

[directory]
read_only = " ro"
style = "blue"

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship"]
format = "$output "

[git_branch]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[status]
style = "red"
symbol = "↵ "
disabled = false

[character]
success_symbol = "[>](bold purple)"
error_symbol = "[>](bold red)"

[python]
symbol = "py "
# pyenv_version_name = false

# Display the version of python from inside a local venv.
#
# Note this will only work when the venv is inside the project and it will only
# work in the directory that contains the venv dir but maybe this is ok?
python_binary = ["./venv/bin/python", "python", "python3", "python2"]

